# Generated by Django 5.1.6 on 2025-02-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_date", models.DateField(auto_now_add=True)),
                ("stock_number", models.CharField(max_length=8)),
                ("last_name", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=20)),
                ("financed", models.BooleanField(default=True)),
                ("reserve", models.FloatField(default=0)),
                ("vsc", models.FloatField(default=0)),
                ("gap", models.FloatField(default=0)),
                ("tw", models.FloatField(default=0)),
                ("tricare", models.FloatField(default=0)),
                ("key", models.FloatField(default=0)),
                (
                    "manager",
                    models.CharField(
                        choices=[
                            ("Victor", "Victor"),
                            ("Kevin", "Kevin"),
                            ("Paul", "Paul"),
                        ],
                        default="Victor",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
